name: Node.js CI

on:
  push:
    branches:
      - Development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install pnpm
      run: npm install -g pnpm
      
    - name: Install Client Dependencies
      run: cd client && pnpm install
    
    - name: Install Server Dependencies
      run: cd server && pnpm install
  
    - name: Run Tests
      run: echo "No tests to run" # cd server && npm test
